#!/usr/bin/env tsx
/**
 * Dumps the datasets to JSON under _export/.
 *
 *   - Each cadastral/geospatial layer -> a GeoJSON FeatureCollection built from
 *     its scraped NDJSON (parcels, addresses, plots, islands, atolls, ...).
 *   - The residents directory -> a plain JSON array read from the database.
 *
 * The residents table holds SYNTHETIC records only (SYN-* ids). No real
 * personal data from the upstream national ID register is scraped or exported.
 */

import { createReadStream } from 'node:fs';
import { mkdir, readFile, writeFile, readdir } from 'node:fs/promises';
import { createInterface } from 'node:readline';
import path from 'node:path';

import { config } from 'dotenv';

import { VISIBLE_RESIDENT } from '../src/lib/censor';
import { resolveDialect, type Dialect } from '../src/lib/dialect';

config({ path: '.env.local', quiet: true });
config({ path: '.env', quiet: true });

const dialect: Dialect = resolveDialect();
const DATA_DIR = path.resolve(process.cwd(), '_scrape/data');
const OUT_DIR = path.resolve(process.cwd(), '_export');

const CRS84 = { type: 'name', properties: { name: 'urn:ogc:def:crs:OGC:1.3:CRS84' } };

async function exportLayers() {
  const files = (await readdir(DATA_DIR)).filter((f) => f.endsWith('.ndjson'));
  const summary: Record<string, number> = {};

  for (const file of files) {
    const key = file.replace(/\.ndjson$/, '');
    const features: unknown[] = [];
    const rl = createInterface({
      input: createReadStream(path.join(DATA_DIR, file)),
      crlfDelay: Infinity,
    });
    for await (const line of rl) {
      if (line.trim()) features.push(JSON.parse(line));
    }

    const collection = {
      type: 'FeatureCollection',
      name: key,
      crs: CRS84,
      features,
    };
    const outPath = path.join(OUT_DIR, `${key}.json`);
    await writeFile(outPath, JSON.stringify(collection));
    summary[key] = features.length;
    console.log(`[export] ${key}.json — ${features.length.toLocaleString()} features`);
  }
  return summary;
}

async function exportResidents() {
  const url = process.env.DATABASE_URL;
  if (!url) {
    console.warn('[export] DATABASE_URL not set — skipping residents export');
    return 0;
  }

  let rows: Record<string, unknown>[] = [];
  // The dump is a published artifact, so it honours the same censorship gate the
  // API applies — see src/lib/censor.ts.
  const sql =
    'SELECT id_no, full_name, dob, gender, permanent_address, island, atoll FROM residents' +
    ` WHERE ${VISIBLE_RESIDENT} ORDER BY id_no`;

  if (dialect === 'postgres') {
    const { Pool } = await import('pg');
    const pool = new Pool({ connectionString: url, max: 2 });
    try {
      rows = (await pool.query(sql)).rows;
    } finally {
      await pool.end();
    }
  } else {
    const { createPool } = await import('mysql2/promise');
    const pool = createPool({ uri: url, connectionLimit: 2, charset: 'utf8mb4' });
    try {
      const [r] = await pool.query(sql);
      rows = r as Record<string, unknown>[];
    } finally {
      await pool.end();
    }
  }

  const payload = {
    note: 'SYNTHETIC data. Generated by scripts/seed-residents.ts. No real personal data.',
    count: rows.length,
    results: rows,
  };
  await writeFile(path.join(OUT_DIR, 'residents.synthetic.json'), JSON.stringify(payload));
  console.log(`[export] residents.synthetic.json — ${rows.length.toLocaleString()} records`);
  return rows.length;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const layers = await exportLayers();
  const residents = await exportResidents();

  const manifest = {
    exportedAt: new Date().toISOString(),
    layers,
    residents: { count: residents, synthetic: true },
  };
  await writeFile(path.join(OUT_DIR, 'manifest.json'), JSON.stringify(manifest, null, 2));
  console.log(`\n[export] wrote ${Object.keys(layers).length} layer files + residents to _export/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
